export enum Errors {
    INVALID_USER_ADD_REQUEST = 1,
    ERROR_WHILE_ADD_DEVICE = 2,
    DEVICE_NOT_FOUND = 3,
    ERROR_WHILE_EDIT_DEVICE = 4,
    INVALID_DEVICE_ADD_REQUEST = 5,
    INVALID_DEVICE_EDIT_REQUEST = 6,
    INVALID_DEVICE_SEARCH_REQUEST = 7,
    USER_NOT_FOUND = 8,
    ERROR_WHILE_ADD_USER = 9,
    INVALID_MEASUREMENT_ADD_REQUEST = 10,
    MEASUREMENT_NOT_FOUND = 11,
    INVALID_ACCESS_TOKEN = 12,
    AUTHORIZATION_ERROR = 13,
    INVALID_MEASUREMENT = 14,
    ERROR_WHILE_ADD_MEASUREMENT = 15
}