export enum Errors {
    INVALID_USER_ADD_REQUEST,
    ERROR_WHILE_ADD_DEVICE,
    DEVICE_NOT_FOUND,
    ERROR_WHILE_EDIT_DEVICE,
    INVALID_DEVICE_ADD_REQUEST,
    INVALID_DEVICE_EDIT_REQUEST,
    INVALID_DEVICE_SEARCH_REQUEST,
    USER_NOT_FOUND,
    ERROR_WHILE_ADD_USER,
    MEASUREMENT_ADD_REQUEST,
    MEASUREMENT_NOT_FOUND
}