export enum DateFormat {
    YYYY_MINUS_MM_MINUS_DD,
    YYYY_SLASH_MM_SLASH_DD,
    MM_SLASH_DD_SLASH_YYYY,
    DD_MINUS_MM_MINUS_YYYY,
    DD_SLASH_MM_SLASH_YYYY,
    MMM_SPACE_DO_SPACE_YY,
    MMMM_SPACE_DO_SPACE_YYYY,
    MM_MINUS_DD_MINUS_YYYY
}